Fix bash autocompletion and support branch completion
To ensure argcomplete can generate bash completion it's necesary to make
sure the call to argcomplete.autocomplete() is performed before checking
any input.

To ensure that we can support calls providing options to git before the
upstream subcommand, add _git_upstream() bash function and some
substitutions to alter the COMP_* variables to be able to pass through
the calls as 'git-upstream ..' instead of 'git ... upstream ..' as the
latter are not understood by argcomplete.

Additionally make sure to pick up if the git bash autocompletion has
detected a different git directory having been set in case the user is
calling as:

  git -C ../<dir>/ upstream ...

It's necessary to make sure that any autocompleting uses the correct
repository location.

Change-Id: Ibb2a7b34579ef3cab258f3c2b27d329087364067

diff --git a/bash_completion/git-upstream b/bash_completion/git-upstream
--- a/bash_completion/git-upstream
+++ b/bash_completion/git-upstream
@@ -1,1 +1,50 @@
 eval "$(register-python-argcomplete git-upstream)"
+# following automatically picked up if git bash completion active
+_git_upstream() {
+    # save originals
+    ORIG_COMP_LINE="${COMP_LINE}"
+    ORIG_COMP_POINT="${COMP_POINT}"
+    ORIG_COMP_WORDS=( "${COMP_WORDS[@]}" )
+
+    # need to modify comp words to strip out git global options
+    # before calling completion on git-upstream
+    NEW_COMP_WORDS=()
+    index=0
+    found=0
+    for i in ${!COMP_WORDS[@]}
+    do
+	[[ "${COMP_WORDS[$i]}" = "upstream" ]] && found=1
+	if [[ ${found} -eq 1 ]]
+	then
+	    NEW_COMP_WORDS[${index}]="${COMP_WORDS[${i}]}"
+	    (( index++ ))
+	fi
+    done
+    NEW_COMP_WORDS[0]="git-upstream"
+    COMP_WORDS=( "${NEW_COMP_WORDS[@]}" )
+    COMP_LINE="${COMP_WORDS[@]}"
+    COMP_POINT="${#COMP_LINE}"
+
+    # check if the git repo path has been passed to git
+    __git_find_repo_path
+    export GIT_UPSTREAM_REPO_PATH="${__git_repo_path}"
+
+    if [[ -n "$_ARC_DEBUG" ]]
+    then
+	echo "COMP_LINE=${COMP_LINE}" >&2
+	echo "COMP_WORDS=${COMP_WORDS[@]}" >&2
+    fi
+
+    # perform completion
+    _python_argcomplete "git-upstream"
+
+    # restore and cleanup
+    COMP_LINE="${ORIG_COMP_LINE}"
+    COMP_POINT="${ORIG_COMP_POINT}"
+    COMP_WORDS=( "${ORIG_COMP_WORDS[@]}" )
+    unset ORIG_COMP_LINE
+    unset ORIG_COMP_POINT
+    unset ORIG_COMP_WORDS
+    unset NEW_COMP_WORDS
+    compopt +o nospace
+}
